## Practical 4 (Panda series)
### Name = Nayan Naresh khuje
### Roll No. = 407

In [1]:
import numpy as np
import  pandas as pd

## 1. Create the following Series and do the specified operations:

#### a) EngAlph, having 26 elements with the alphabets as values and default index values.

In [2]:
alf= pd.Series(['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'])

In [3]:
alf.head() # print only starting 5 colomns

0    a
1    b
2    c
3    d
4    e
dtype: object

#### b) Vowels, having 5 elements with index labels ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’ and all the five values set to zero. Check if it is an empty series.

In [4]:
vow=pd.Series(0,index=['a','e','i','o','u'])

In [5]:
vow

a    0
e    0
i    0
o    0
u    0
dtype: int64

#### c) Friends, from a dictionary having roll numbers of five of your friends as data and their first name as keys.


In [6]:
fd={'sahil':413,'anjali':414,'shalu':5646,'Shrutika':403,'arpit':404}
fds=pd.Series(fd)
fds

sahil        413
anjali       414
shalu       5646
Shrutika     403
arpit        404
dtype: int64

#### d) MTseries, an empty Series. Check if it is an empty series.

In [7]:
MTseries = pd.Series()
MTseries

Series([], dtype: float64)

#### e) MonthDays, from a numpy array having the number of days in the 12 months of a year. The labels should be the month numbers from 1 to 12.

In [8]:
MonthDays = pd.Series(np.array([31,28,31,30,31,30,31,31,30,31,30,31]),index=[1,2,3,4,5,6,7,8,9,10,11,12])
print(MonthDays)

1     31
2     28
3     31
4     30
5     31
6     30
7     31
8     31
9     30
10    31
11    30
12    31
dtype: int32


## 2. Using the Series created in Question 1, write commands for the following:


#### a) Set all the values of Vowels to 10 and display the Series.

In [9]:
vow['a':'u']=10
vow

a    10
e    10
i    10
o    10
u    10
dtype: int64

#### b) Divide all values of Vowels by 2 and display the Series.

In [10]:
div=vow/2
div

a    5.0
e    5.0
i    5.0
o    5.0
u    5.0
dtype: float64

#### c) Create another series Vowels1 having 5 elements with index labels ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’ having values [2,5,6,3,8] respectively.

In [11]:
vowels1 = pd.Series([2,5,6,3,8],index=['a','e','i','o','u'])
vowels1

a    2
e    5
i    6
o    3
u    8
dtype: int64

#### d) Add Vowels and Vowels1 and assign the result to Vowels3

In [12]:
vowaddition=vow+vowels1 # addition
vowaddition

a    12
e    15
i    16
o    13
u    18
dtype: int64

#### e) Subtract, Multiply and Divide Vowels by Vowels1.

In [13]:
print("subtraction")
subt=vow-vowels1 #Subtraction
print(subt)
mult=vow*vowels1 #multiplication
print("multiplication")
print(mult)


subtraction
a    8
e    5
i    4
o    7
u    2
dtype: int64
multiplication
a    20
e    50
i    60
o    30
u    80
dtype: int64


#### f) Alter the labels of Vowels1 to [‘A’, ‘E’, ‘I’, ‘O’, ‘U’]

In [14]:
vowels1.index=['A','E','I','O','U']
vowels1

A    2
E    5
I    6
O    3
U    8
dtype: int64

## 3. Using the Series created in Question 1, write commands for the following:

#### a) Find the dimensions, size and values of the Series EngAlph, Vowels, Friends, MTseries, MonthDays.

In [15]:
#for EngAlph
print(alf.ndim)# for dimensions
print(alf.size) #for size
print(alf.values)#for values

1
26
['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q' 'r'
 's' 't' 'u' 'v' 'w' 'x' 'y' 'z']


In [16]:
#for Vowels
print(vow.ndim)# for dimensions
print(vow.size) #for size
print(vow.values)#for values

1
5
[10 10 10 10 10]


In [17]:
#for Friends
print(fds.ndim)# for dimensions
print(fds.size) #for size
print(fds.values)#for values

1
5
[ 413  414 5646  403  404]


In [18]:
#for MTseries
print(MTseries.ndim)# for dimensions
print(MTseries.size) #for size
print(MTseries.values)#for values

1
0
[]


In [19]:
#for MonthDays
print(MonthDays.ndim)# for dimensions
print(MonthDays.size) #for size
print(MonthDays.values)#for values

1
12
[31 28 31 30 31 30 31 31 30 31 30 31]


#### b) Rename the Series MTseries as SeriesEmpty

In [20]:
SeriesEmpty=MTseries.rename()
print(SeriesEmpty)

Series([], dtype: float64)


#### c) Name the index of the Series MonthDays as monthno and that of Series Friends as Fname.

In [28]:
MonthDays.index.name=("monthno")
MonthDays

monthno
jan      31
feb      28
march    31
april    30
may      31
june     30
july     31
aug      31
sept     30
oct      31
now      30
dec      31
dtype: int32

In [30]:
fds.index.name=("fname")
fds

fname
sahil        413
anjali       414
shalu       5646
Shrutika     403
arpit        404
dtype: int64

#### d) Display the 3rd and 2nd value of the Series Notes Friends, in that order.


In [25]:
fds['Shrutika'] #for 3rd 

403

In [26]:
fds['shalu'] #for 2nd

5646

#### e) Display the alphabets ‘e’ to ‘p’ from the Series EngAlph.